# 1.RL Sample Average Method

In [1]:
import torch   
import random
torch.manual_seed(100)



In [2]:
if torch.cuda.is_available():
    device = "cuda"

device

'cuda'

In [3]:
BATCH_SIZE = 100
BATCH_SIZE

100

In [4]:
actions = torch.randint(1 , 6 , (BATCH_SIZE,) , device=device)
actions

tensor([3, 3, 5, 3, 1, 3, 2, 5, 2, 5, 5, 1, 4, 5, 4, 3, 3, 5, 2, 2, 5, 5, 1, 5,
        2, 4, 5, 5, 2, 5, 1, 2, 5, 4, 1, 1, 5, 4, 2, 3, 2, 1, 2, 2, 1, 2, 1, 2,
        1, 1, 4, 5, 3, 1, 5, 5, 5, 5, 1, 2, 1, 3, 2, 1, 2, 4, 3, 2, 1, 2, 3, 4,
        2, 5, 5, 2, 1, 4, 5, 4, 3, 5, 3, 2, 5, 1, 1, 1, 5, 1, 1, 2, 1, 5, 3, 3,
        2, 4, 3, 3], device='cuda:0')

In [5]:
actions.shape

torch.Size([100])

In [6]:
rewards = torch.rand((BATCH_SIZE,) , device=device)
rewards

tensor([0.8344, 0.7001, 0.5361, 0.8883, 0.0220, 0.7938, 0.7543, 0.6514, 0.9609,
        0.8294, 0.3537, 0.8665, 0.2563, 0.5770, 0.0433, 0.0837, 0.6263, 0.5618,
        0.6589, 0.4808, 0.6172, 0.5818, 0.0753, 0.0792, 0.0765, 0.2946, 0.1289,
        0.1717, 0.3002, 0.7698, 0.4647, 0.7871, 0.2272, 0.2296, 0.0723, 0.7259,
        0.2371, 0.4740, 0.7083, 0.0154, 0.9985, 0.1717, 0.7336, 0.3570, 0.6377,
        0.0669, 0.0436, 0.3026, 0.4370, 0.5717, 0.2362, 0.5862, 0.7265, 0.2540,
        0.1194, 0.1819, 0.5693, 0.9899, 0.5516, 0.3524, 0.3854, 0.4761, 0.2965,
        0.8352, 0.4146, 0.6716, 0.3455, 0.8389, 0.5062, 0.7360, 0.8370, 0.6655,
        0.5389, 0.7631, 0.3010, 0.3146, 0.1132, 0.4187, 0.3295, 0.4154, 0.9915,
        0.2093, 0.6067, 0.3841, 0.7249, 0.7976, 0.1511, 0.6984, 0.8953, 0.1742,
        0.8720, 0.3984, 0.4770, 0.8990, 0.9964, 0.0501, 0.4891, 0.5103, 0.9123,
        0.3186], device='cuda:0')

In [7]:
rewards.shape

torch.Size([100])

In [8]:
actions_rewards = torch.stack(  (actions , rewards) , dim=1)
actions_rewards

tensor([[3.0000, 0.8344],
        [3.0000, 0.7001],
        [5.0000, 0.5361],
        [3.0000, 0.8883],
        [1.0000, 0.0220],
        [3.0000, 0.7938],
        [2.0000, 0.7543],
        [5.0000, 0.6514],
        [2.0000, 0.9609],
        [5.0000, 0.8294],
        [5.0000, 0.3537],
        [1.0000, 0.8665],
        [4.0000, 0.2563],
        [5.0000, 0.5770],
        [4.0000, 0.0433],
        [3.0000, 0.0837],
        [3.0000, 0.6263],
        [5.0000, 0.5618],
        [2.0000, 0.6589],
        [2.0000, 0.4808],
        [5.0000, 0.6172],
        [5.0000, 0.5818],
        [1.0000, 0.0753],
        [5.0000, 0.0792],
        [2.0000, 0.0765],
        [4.0000, 0.2946],
        [5.0000, 0.1289],
        [5.0000, 0.1717],
        [2.0000, 0.3002],
        [5.0000, 0.7698],
        [1.0000, 0.4647],
        [2.0000, 0.7871],
        [5.0000, 0.2272],
        [4.0000, 0.2296],
        [1.0000, 0.0723],
        [1.0000, 0.7259],
        [5.0000, 0.2371],
        [4.0000, 0.4740],
        [2.0

In [9]:
actions_rewards[actions_rewards[: , 0] == 5.0]

tensor([[5.0000, 0.5361],
        [5.0000, 0.6514],
        [5.0000, 0.8294],
        [5.0000, 0.3537],
        [5.0000, 0.5770],
        [5.0000, 0.5618],
        [5.0000, 0.6172],
        [5.0000, 0.5818],
        [5.0000, 0.0792],
        [5.0000, 0.1289],
        [5.0000, 0.1717],
        [5.0000, 0.7698],
        [5.0000, 0.2272],
        [5.0000, 0.2371],
        [5.0000, 0.5862],
        [5.0000, 0.1194],
        [5.0000, 0.1819],
        [5.0000, 0.5693],
        [5.0000, 0.9899],
        [5.0000, 0.7631],
        [5.0000, 0.3010],
        [5.0000, 0.3295],
        [5.0000, 0.2093],
        [5.0000, 0.7249],
        [5.0000, 0.8953],
        [5.0000, 0.8990]], device='cuda:0')

In [10]:
mean_rewards = torch.stack([rewards[actions == i].mean() for i in actions.unique()])
mean_rewards

tensor([0.4306, 0.5195, 0.6002, 0.3832, 0.4958], device='cuda:0')

### 1.1 Increamental Update Rule for non stationary enviroments : <math xmlns="http://www.w3.org/1998/Math/MathML" display="block"><semantics><mrow><msub><mi>Q</mi><mrow><mi>n</mi><mo>+</mo><mn>1</mn></mrow></msub><mo>=</mo><msub><mi>Q</mi><mi>n</mi></msub><mo>+</mo><mi>α</mi><mo stretchy="false">(</mo><msub><mi>R</mi><mi>n</mi></msub><mo>−</mo><msub><mi>Q</mi><mi>n</mi></msub><mo stretchy="false">)</mo></mrow><annotation encoding="application/x-tex">Q_{n+1} = Q_n + \alpha (R_n - Q_n) 
</annotation></semantics></math>

( Q_n ) is the current estimate of the action value.
( R_n ) is the reward received after taking the action.
( alpha ) is the step size parameter, which determines how much weight to give to the new reward compared to the old estimate2.


In [11]:
def update(qn , a , rn ):

    try:
        for i in range(len(rn)):
            qn = qn + a * (rn[i] - qn)
            print(qn)
        return qn

    except:
        qn_1 = qn + a * (rn - qn)
        return qn_1

    

rn = torch.tensor(0.9 , device=device )
qn = mean_rewards[0]
a = torch.tensor(1/len(actions_rewards) , device= device)

In [12]:
qn

tensor(0.4306, device='cuda:0')

In [13]:
qn_1 = update(qn ,a , rn)
qn_1

tensor(0.4353, device='cuda:0')

### Experiement 

In [14]:
qn = torch.tensor(5 , device=device)
a = torch.tensor(0.5 , device=device)
rn = torch.randint(0 , 2 , (100,) , device=device)
rn

tensor([1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0,
        0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
        0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0,
        0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1,
        1, 1, 0, 0], device='cuda:0')

In [15]:
#### The q0 value got updated based on our rewards , missing aroudn with qn initial value affects the process naking the agent more optimistic or pessemstic 

In [16]:
qn = update(qn ,a , rn)
qn

tensor(3., device='cuda:0')
tensor(2., device='cuda:0')
tensor(1., device='cuda:0')
tensor(1., device='cuda:0')
tensor(1., device='cuda:0')
tensor(1., device='cuda:0')
tensor(0.5000, device='cuda:0')
tensor(0.7500, device='cuda:0')
tensor(0.8750, device='cuda:0')
tensor(0.4375, device='cuda:0')
tensor(0.2188, device='cuda:0')
tensor(0.1094, device='cuda:0')
tensor(0.0547, device='cuda:0')
tensor(0.0273, device='cuda:0')
tensor(0.5137, device='cuda:0')
tensor(0.2568, device='cuda:0')
tensor(0.1284, device='cuda:0')
tensor(0.0642, device='cuda:0')
tensor(0.0321, device='cuda:0')
tensor(0.5161, device='cuda:0')
tensor(0.7580, device='cuda:0')
tensor(0.8790, device='cuda:0')
tensor(0.4395, device='cuda:0')
tensor(0.2198, device='cuda:0')
tensor(0.1099, device='cuda:0')
tensor(0.5549, device='cuda:0')
tensor(0.7775, device='cuda:0')
tensor(0.8887, device='cuda:0')
tensor(0.4444, device='cuda:0')
tensor(0.2222, device='cuda:0')
tensor(0.6111, device='cuda:0')
tensor(0.3055, device='cuda:0')


tensor(0.2255, device='cuda:0')

### Epsilon Greedy Agent Example

<math xmlns="http://www.w3.org/1998/Math/MathML" display="block"><semantics><mrow><msub><mi>Q</mi><mrow><mi>n</mi><mo>+</mo><mn>1</mn></mrow></msub><mo>=</mo><msub><mi>Q</mi><mi>n</mi></msub><mo>+</mo><mi>α</mi><mo stretchy="false">(</mo><msub><mi>R</mi><mi>n</mi></msub><mo>−</mo><msub><mi>Q</mi><mi>n</mi></msub><mo stretchy="false">)</mo></mrow><annotation encoding="application/x-tex">Q_{n+1} = Q_n + \alpha (R_n - Q_n) 
</annotation></semantics></math>

#### Training

In [17]:
actions = torch.tensor([0 ,1] , device= device )
Q = torch.tensor([5, 5] , device=device , dtype=float)
BATCH_SIZE = 100
EPS = 0.1
a = 0.5
probabilities = torch.tensor([0.2, 0.8], device=device)  # 70% for action 0, 30% for action 1

# Sample actions based on the defined probabilities
actions_samples = torch.multinomial(probabilities, BATCH_SIZE, replacement=True )
actions_samples

tensor([0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1,
        1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0,
        1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0,
        1, 1, 0, 1], device='cuda:0')

In [18]:
rewards_samples = torch.multinomial(probabilities, BATCH_SIZE, replacement=True )
rewards_samples = torch.tensor(rewards_samples , device=device ,dtype=torch.float)
rewards_samples




C:\Users\Jamil\AppData\Local\Temp\ipykernel_12440\363706602.py:2: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  rewards_samples = torch.tensor(rewards_samples , device=device ,dtype=torch.float)


tensor([1., 0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0., 1., 1., 1., 1., 1., 0.,
        0., 1., 1., 1., 0., 0., 1., 1., 0., 1., 1., 1., 1., 0., 1., 1., 0., 1.,
        1., 1., 0., 1., 1., 1., 0., 1., 0., 1., 1., 0., 1., 0., 1., 1., 1., 1.,
        1., 0., 1., 1., 1., 0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        0., 1., 0., 0., 1., 1., 1., 1., 0., 1.], device='cuda:0')

In [19]:

for i in range(BATCH_SIZE):

    if random.random() > EPS :

        reward = rewards_samples[i]
        action = actions_samples[i]
        Q[int(action)] = update(Q[int(action)] ,a , reward)

    else :
        action = torch.argmax(Q , dim=0)

        if action == actions_samples[i]:
            reward = rewards_samples[i]
            Q[int(action)] = update(Q[int(action)] ,a , reward)
        
        else:
            reward = torch.tensor(0 , device=device , dtype=torch.float) 
            Q[int(action)] = update(Q[int(action)] ,a , reward)
    
    print(Q[0].item() , Q[1].item() , reward.item() ," Action : " ,action.item())
        


3.0 5.0 1.0  Action :  0
3.0 2.5 0.0  Action :  1
3.0 1.75 1.0  Action :  1
3.0 1.375 1.0  Action :  1
2.0 1.375 1.0  Action :  0
2.0 1.1875 1.0  Action :  1
1.5 1.1875 1.0  Action :  0
1.25 1.1875 1.0  Action :  0
1.25 1.09375 1.0  Action :  1
1.25 1.046875 1.0  Action :  1
1.25 1.0234375 1.0  Action :  1
1.25 1.01171875 1.0  Action :  1
1.125 1.01171875 1.0  Action :  0
1.125 1.005859375 1.0  Action :  1
1.0625 1.005859375 1.0  Action :  0
1.0625 1.0029296875 1.0  Action :  1
1.03125 1.0029296875 1.0  Action :  0
1.015625 1.0029296875 1.0  Action :  0
1.0078125 1.0029296875 1.0  Action :  0
0.50390625 1.0029296875 0.0  Action :  0
0.50390625 1.00146484375 1.0  Action :  1
0.751953125 1.00146484375 1.0  Action :  0
0.751953125 1.000732421875 1.0  Action :  1
0.751953125 1.0003662109375 1.0  Action :  1
0.751953125 1.00018310546875 1.0  Action :  1
0.751953125 1.000091552734375 1.0  Action :  1
0.751953125 1.0000457763671875 1.0  Action :  1
0.751953125 1.0000228881835938 1.0  Action :

#### Evaluation

In [20]:
def evaluate_agent():

        EVAL_TIME_STEPS = 100
        TOTAL_REWARD = 0
        N_EPISODES = 10
        action = torch.argmax(Q , dim=0)
        print("Chosen action is" , int(action))

        for i in range(N_EPISODES):
                EPISODE_REWARD = 0
                for i in range(EVAL_TIME_STEPS):

                        action = torch.argmax(Q , dim=0)
                        random_index_sample = random.randint(0 , len(actions_samples) - 1)

                        if action == actions_samples[random_index_sample]:
                                reward = rewards_samples[random_index_sample]
                        else :
                                reward = torch.tensor(0 , device=device , dtype=torch.float)
                        
                        EPISODE_REWARD+=reward
                print("Episode Reward" , EPISODE_REWARD)

                TOTAL_REWARD+=EPISODE_REWARD



        print("Mean Reward: ", (TOTAL_REWARD / N_EPISODES).item()  )



In [21]:
evaluate_agent()

Chosen action is 1
Episode Reward tensor(64., device='cuda:0')
Episode Reward tensor(65., device='cuda:0')
Episode Reward tensor(59., device='cuda:0')
Episode Reward tensor(60., device='cuda:0')
Episode Reward tensor(58., device='cuda:0')
Episode Reward tensor(69., device='cuda:0')
Episode Reward tensor(60., device='cuda:0')
Episode Reward tensor(66., device='cuda:0')
Episode Reward tensor(55., device='cuda:0')
Episode Reward tensor(52., device='cuda:0')
Mean Reward:  60.79999923706055


### Upper confidence bound

### <math xmlns="http://www.w3.org/1998/Math/MathML" display="block"><semantics><mrow><msub><mi>A</mi><mi>t</mi></msub><mo>=</mo><mi>arg</mi><mo>⁡</mo><munder><mrow><mi>max</mi><mo>⁡</mo></mrow><mi>a</mi></munder><mrow><mo fence="true">(</mo><msub><mi>Q</mi><mi>t</mi></msub><mo stretchy="false">(</mo><mi>a</mi><mo stretchy="false">)</mo><mo>+</mo><mi>c</mi><msqrt><mfrac><mrow><mi>ln</mi><mo>⁡</mo><mi>t</mi></mrow><mrow><msub><mi>N</mi><mi>t</mi></msub><mo stretchy="false">(</mo><mi>a</mi><mo stretchy="false">)</mo></mrow></mfrac></msqrt><mo fence="true">)</mo></mrow></mrow><annotation encoding="application/x-tex">A_t = \arg\max_a \left( Q_t(a) + c \sqrt{\frac{\ln t}{N_t(a)}} \right)
</annotation></semantics></math>

<math xmlns=“http://www.w3.org/1998/Math/MathML” display=“inline”><semantics><mrow><msub><mi>Q</mi><mi>t</mi></msub><mo stretchy=“false”>(</mo><mi>a</mi><mo stretchy=“false”>)</mo></mrow><annotation encoding=“application/x-tex”>Q_t(a)</annotation></semantics></math>: This is the estimated value of action ( a ) at time ( t ). It represents the average reward received from action ( a ) up to time ( t ).
<math xmlns=“http://www.w3.org/1998/Math/MathML” display=“inline”><semantics><mrow><mi>c</mi></mrow><annotation encoding=“application/x-tex”>c</annotation></semantics></math>: This is a constant that controls the degree of exploration. A higher value of ( c ) encourages more exploration.
<math xmlns=“http://www.w3.org/1998/Math/MathML” display=“inline”><semantics><mrow><msqrt><mfrac><mrow><mi>ln</mi><mo>⁡</mo><mi>t</mi></mrow><mrow><msub><mi>N</mi><mi>t</mi></msub><mo stretchy=“false”>(</mo><mi>a</mi><mo stretchy=“false”>)</mo></mrow></mfrac></msqrt></mrow><annotation encoding=“application/x-tex”>\sqrt{\frac{\ln t}{N_t(a)}}</annotation></semantics></math>: This is the exploration term. It increases as the number of times action ( a ) has been selected, ( N_t(a) ), decreases. It also increases with the logarithm of the current time step ( t ), encouraging exploration of less frequently chosen actions.
<math xmlns=“http://www.w3.org/1998/Math/MathML” display=“inline”><semantics><mrow><mi>arg</mi><mo>⁡</mo><munder><mrow><mi>max</mi><mo>⁡</mo></mrow><mi>a</mi></munder></mrow><annotation encoding=“application/x-tex”>\arg\max_a</annotation></semantics></math>: This notation means that we select the action ( a ) that maximizes the entire expression.

In [22]:
c = 2
Q = torch.tensor([5, 5] , device=device , dtype=float)
i =0

actions_freq = torch.ones((2,) , device=device , dtype=torch.float)

def upper_confidence_bound(Q , c , t , nt_a):

    for i in range(len(Q)):
          
          Q[i] = Q[i] + c * (   torch.sqrt( torch.log(t)  ) /  nt_a[i]      )
    return Q

for i in range(BATCH_SIZE):

    
    action = torch.argmax( upper_confidence_bound(Q , c ,torch.tensor(i+1 , device=device) , actions_freq) , dim=0)

    if action == actions[0]:

        actions_freq[0]+= torch.tensor(1 , device=device , dtype=torch.float)
    else :
        actions_freq[1]+= torch.tensor(1 , device=device , dtype=torch.float)       

    if action == actions_samples[i]:
            reward = rewards_samples[i]
            Q[int(action)] = update(Q[int(action)] ,a , reward)
        
    else:
            reward = torch.tensor(0 , device=device , dtype=torch.float) 
            Q[int(action)] = update(Q[int(action)] ,a , reward)
    
    print(Q[0].item() , Q[1].item() , reward.item() ," Action : " ,action.item())

3.0 5.0 1.0  Action :  0
3.8325546383857727 3.3325546383857727 0.0  Action :  1
2.4403508603572845 4.380701720714569 0.0  Action :  0
3.2252908647060394 3.2790558636188507 1.0  Action :  1
4.071048349142075 2.062406674027443 0.0  Action :  1
2.481712892651558 2.731689766049385 0.0  Action :  0
3.1791923195123672 1.7145845964550972 0.0  Action :  1
2.450102873146534 2.2913953140378 1.0  Action :  0
1.5215122140944004 2.8843168690800667 0.0  Action :  0
2.027321223169565 2.2456438578665257 1.0  Action :  1
2.5434924997389317 1.880907567217946 1.0  Action :  1
1.534472705796361 2.331295760348439 0.0  Action :  0
1.992057265713811 1.3944401601329446 0.0  Action :  1
1.2281025657430291 1.8005695501342416 0.0  Action :  0
1.6395064303651452 1.1059867073781788 0.0  Action :  1
1.0278918747790158 1.4760110010392964 0.0  Action :  0
1.401939690578729 0.9250294084195048 0.0  Action :  1
1.3898708822671324 1.265051286900416 1.0  Action :  0
1.3665291221113876 1.6082386488560587 1.0  Action :  0
1

In [23]:
evaluate_agent()

Chosen action is 1
Episode Reward tensor(69., device='cuda:0')
Episode Reward tensor(65., device='cuda:0')
Episode Reward tensor(58., device='cuda:0')
Episode Reward tensor(65., device='cuda:0')
Episode Reward tensor(58., device='cuda:0')
Episode Reward tensor(63., device='cuda:0')
Episode Reward tensor(58., device='cuda:0')
Episode Reward tensor(60., device='cuda:0')
Episode Reward tensor(60., device='cuda:0')
Episode Reward tensor(57., device='cuda:0')
Mean Reward:  61.29999923706055


# Decaying Past Rewards

$$
Q = (1 - \alpha)^n Q_1 + \sum_{i=1}^{n} \alpha(1 - \alpha)^{n-i} R_i
$$


# Expected returns
 The Expected retruns over the episode is used for the agent to maximize, the expected concept is used since the state rewards must be represented in probabilities and are not certain
 # <math xmlns="http://www.w3.org/1998/Math/MathML" display="block"><semantics><mrow><mi mathvariant="double-struck">E</mi><mo stretchy="false">[</mo><mi>R</mi><mo stretchy="false">]</mo><mo>=</mo><munderover><mo>∑</mo><mrow><mi>i</mi><mo>=</mo><mn>1</mn></mrow><mi>n</mi></munderover><msub><mi>p</mi><mi>i</mi></msub><mo>⋅</mo><msub><mi>r</mi><mi>i</mi></msub></mrow><annotation encoding="application/x-tex">\mathbb{E}[R] = \sum_{i=1}^{n} p_i \cdot r_i
</annotation></semantics></math>

# <math xmlns="http://www.w3.org/1998/Math/MathML" display="block"><semantics><mrow><mi mathvariant="double-struck">E</mi><mo stretchy="false">[</mo><mi>R</mi><mo stretchy="false">]</mo><mo>=</mo><msubsup><mo>∫</mo><mi>a</mi><mi>b</mi></msubsup><mi>r</mi><mo>⋅</mo><mi>p</mi><mo stretchy="false">(</mo><mi>r</mi><mo stretchy="false">)</mo><mtext> </mtext><mi>d</mi><mi>r</mi></mrow><annotation encoding="application/x-tex">\mathbb{E}[R] = \int_{a}^{b} r \cdot p(r) \, dr
</annotation></semantics></math>

# Reward Recursive Equation

# <math xmlns="http://www.w3.org/1998/Math/MathML" display="block"><semantics><mrow><msub><mi>G</mi><mi>t</mi></msub><mo>=</mo><msub><mi>R</mi><mrow><mi>t</mi><mo>+</mo><mn>1</mn></mrow></msub><mo>+</mo><mi>γ</mi><msub><mi>G</mi><mrow><mi>t</mi><mo>+</mo><mn>1</mn></mrow></msub></mrow><annotation encoding="application/x-tex">G_t = R_{t+1} + \gamma G_{t+1}
</annotation></semantics></math>

<math xmlns="http://www.w3.org/1998/Math/MathML" display="block"><semantics><mtable rowspacing="0.25em" columnalign="right left" columnspacing="0em"><mtr><mtd><mstyle scriptlevel="0" displaystyle="true"><mrow><mo stretchy="false">(</mo><msub><mi>G</mi><mi>t</mi></msub><mo stretchy="false">)</mo></mrow></mstyle></mtd><mtd><mstyle scriptlevel="0" displaystyle="true"><mrow><mrow></mrow><mo>:</mo><mtext>Expected&nbsp;return&nbsp;at&nbsp;time&nbsp;</mtext><mo stretchy="false">(</mo><mi>t</mi><mo stretchy="false">)</mo><mi mathvariant="normal">.</mi></mrow></mstyle></mtd></mtr><mtr><mtd><mstyle scriptlevel="0" displaystyle="true"><mrow><mo stretchy="false">(</mo><msub><mi>R</mi><mrow><mi>t</mi><mo>+</mo><mn>1</mn></mrow></msub><mo stretchy="false">)</mo></mrow></mstyle></mtd><mtd><mstyle scriptlevel="0" displaystyle="true"><mrow><mrow></mrow><mo>:</mo><mtext>Reward&nbsp;received&nbsp;at&nbsp;time&nbsp;</mtext><mo stretchy="false">(</mo><mi>t</mi><mo>+</mo><mn>1</mn><mo stretchy="false">)</mo><mi mathvariant="normal">.</mi></mrow></mstyle></mtd></mtr><mtr><mtd><mstyle scriptlevel="0" displaystyle="true"><mrow><mo stretchy="false">(</mo><mi>γ</mi><mo stretchy="false">)</mo></mrow></mstyle></mtd><mtd><mstyle scriptlevel="0" displaystyle="true"><mrow><mrow></mrow><mo>:</mo><mtext>Discount&nbsp;factor,&nbsp;</mtext><mo stretchy="false">(</mo><mn>0</mn><mo>≤</mo><mi>γ</mi><mo>≤</mo><mn>1</mn><mo stretchy="false">)</mo><mi mathvariant="normal">.</mi></mrow></mstyle></mtd></mtr><mtr><mtd><mstyle scriptlevel="0" displaystyle="true"><mrow><mo stretchy="false">(</mo><msub><mi>G</mi><mrow><mi>t</mi><mo>+</mo><mn>1</mn></mrow></msub><mo stretchy="false">)</mo></mrow></mstyle></mtd><mtd><mstyle scriptlevel="0" displaystyle="true"><mrow><mrow></mrow><mo>:</mo><mtext>Expected&nbsp;return&nbsp;at&nbsp;time&nbsp;</mtext><mo stretchy="false">(</mo><mi>t</mi><mo>+</mo><mn>1</mn><mo stretchy="false">)</mo><mi mathvariant="normal">.</mi></mrow></mstyle></mtd></mtr></mtable><annotation encoding="application/x-tex">\begin{align*}
( G_t ) &amp;: \text{Expected return at time } ( t ). \\
( R_{t+1} ) &amp;: \text{Reward received at time } ( t+1 ). \\
( \gamma ) &amp;: \text{Discount factor, } ( 0 \leq \gamma \leq 1 ). \\
( G_{t+1} ) &amp;: \text{Expected return at time } ( t+1 ).
\end{align*}
</annotation></semantics></math>

#### The second term is the function calling itself on time step t+1

In [24]:
rewards = torch.tensor([1,1,1,1,1] , device=device)
y = torch.tensor(0.8 , device=device)

def calculate_reward(rt , y):

    gt = 0
    t = 0
    
    for reward in rt:
         gt+= y **t * reward
         t+=1
    
    return gt

 
    
gt = calculate_reward(rewards , y )

print(gt)

tensor(3.3616, device='cuda:0')


# Note : The number of possible determinstic policies are equal to the number of actions ^ number of possible states

# Determenstic value function update bellman equation

In [25]:
from TabularDiscrete import TabularEnv
env = TabularEnv()
state , _ = env.reset()

P = torch.tensor( [0.5 , 0.5] , device=device , dtype=torch.float)

In [26]:
V = torch.tensor(env.table.values , device=device , dtype=torch.float)[: , 2]
V


tensor([0.6044, 0.2589], device='cuda:0')

In [27]:
R = V.clone()
R

tensor([0.6044, 0.2589], device='cuda:0')

In [28]:
def update_value_determenstic(R , gamma , V ):
    return R + gamma * (P * V)


gamma = 0.8

V_prime =update_value_determenstic(R , gamma , V)
V_prime

tensor([0.8462, 0.3624], device='cuda:0')

# R + γ P max_a’ Q

### ( R ) is a matrix of expected rewards for all state-action pairs.
( \gamma ) is the discount factor.
( P ) is the transition probability matrix.
( \max_{a’} Q ) is a vector where each element represents the maximum action-value for the next state ( s’ ) over all possible actions ( a’ ).
